Ux fixes
goatandsheep/beatcaps-react pull request #76
Opened 2021-01-21 20:07 UTC by lindajzhao

Fixes: #72

2021-01-28 22:45 UTC, goatandsheep requested changes

2021-01-28 22:45 UTC, goatandsheep commented on src/pages/TemplateWizard.js
> +          <p className="subtitle is-4">Choose videos for each view</p>
Why do we remove the legend?

2021-01-29 00:33 UTC, lindajzhao commented on src/pages/TemplateWizard.js
> +          <p className="subtitle is-4">Choose videos for each view</p>
Good catch! I put it back in!

2021-01-29 02:17 UTC, goatandsheep approved these changes

2021-01-29 02:17 UTC, merged